### PR TITLE
travis: Deploy packages to BinTray for tags

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
When tags are built, packages will be created and uploaded to BinTray automatically (to https://bintray.com/sociomantic-tsunami/nodes/dmqnode).

DHT node commit: https://github.com/sociomantic-tsunami/dhtnode/pull/44/commits/8de577a3f94ba87b7efec1cbbfd35e0c315dfcc0

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
This should target v1.7.x I think.

**Comment by nemanja-boric-sociomantic** [comment]
@gavin-norman-sociomantic could you double check this, as might be too biased?

**Comment by nemanja-boric-sociomantic** [comment]
Except the branch, LGTM.

**Comment by david-eckardt-sociomantic** [comment]
Changed base.

**Pull request merged**
