### PR TITLE
Update to beaver v0.4.0

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Test PR to see if the test still hangs as described in #41.

### CODE REVIEW

**Comment by david-eckardt-sociomantic** [comment]
It is https://github.com/sociomantic-tsunami/beaver/commit/61aebb1e7984c02c9b170a4a3040334fee824a2c. `dmqtest` hangs while `loadfiles` and `ovfminimize` pass.

**Comment by david-eckardt-sociomantic** [comment]
https://github.com/sociomantic-tsunami/beaver/pull/50 fixes it.
@leandro-lucarella-sociomantic, FYI: sociomantic-tsunami/beaver@61aebb1 makes the Travis builds of this PR with `F=production` hang; `F=devel` tests pass. Printouts show that `test-dmqtest` hangs while the other integration tests finish. I don't know if `allunittests` finishes or hangs.

**Comment by gavin-norman-sociomantic** [comment]
Great to have found the guilty commit! Any idea why it has this effect?

**Comment by david-eckardt-sociomantic** [comment]
Enabling verbosity shows that `PreConsumeChecker` tests hang. And indeed, disabling the `PreConsumeChecker` tests in `dmqproto`/`dmqtest.cases.WriterChecker` fixes it.
There is also a [code comment in `ConsumeChecker`](https://github.com/sociomantic-tsunami/dmqproto/blob/v14.x.x/src/dmqtest/cases/checkers/ConsumeChecker.d#L114-L118) saying that tests could hang "in error situations (if the node doesn't send any records to the consumer)".

**Comment by david-eckardt-sociomantic** [comment]
> Mmm, so it seems like beaver just exposed some bad behaviour and is not a problem in beaver itself?

Yes. The consumer tests are inherently prone to hang, and the change in beaver to run the unittests in parallel with the integration tests seems to trigger it.

**Comment by leandro-lucarella-sociomantic** [comment]
Ha! I love those parallel tests that are always breaking weaknesses in tests :trollface:

**Comment by nemanja-boric-sociomantic** [comment]
Only because they are not your tests to fail ;-)

**Comment by david-eckardt-sociomantic** [comment]
Fixed in https://github.com/sociomantic-tsunami/dmqproto/pull/60.

**Comment by david-eckardt-sociomantic** [comment]
Superseded by #56, which has been merged. Closing.

**Pull request closed without merging**
