### PR TITLE
Neo stage 2 D2 migration 

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Cherry-picked commits from #5 and #13.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
I wonder if it's possible/better just to merge `master` into `neo`?

**Comment by david-eckardt-sociomantic** [comment]
> I wonder if it's possible/better just to merge `master` into `neo`?

You're right. Updated.

**Comment by gavin-norman-sociomantic** [comment]
Am I right that this PR is now simply a merge and did not require any additional changes?

**Comment by gavin-norman-sociomantic** [comment]
Ah just saw this is already merged. Good :)

**Comment by mihails-strasuns-sociomantic** [comment]
NB: it doesn't matter now but you should eventually rebase neo branch on the major branch it will target

**Comment by nemanja-boric-sociomantic** [comment]
But what if we already have the tags released on the `neo` branch?

**Comment by mihails-strasuns-sociomantic** [comment]
They will remain to be available, git GC can't collect named objects until you delete them,

**Comment by mihails-strasuns-sociomantic** [comment]
(this is why we release v4 alphas in ocean)

**Comment by david-eckardt-sociomantic** [comment]
> Am I right that this PR is now simply a merge and did not require any additional changes?

That's right.

**Pull request merged**
