### PR TITLE
[DO NOT MERGE] Merge neo

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
- Merge [`neo-beta-3`](https://github.com/sociomantic-tsunami/dmqnode/releases/tag/neo-beta-3).
- Update submodules.
  - Update to new node request handler framework in dmqproto v14.0.1/swarm v5.0.3

Dmqproto v14.1.0 has not been released yet, https://github.com/sociomantic-tsunami/dmqproto/pull/52 is currently pending. Blocked until v14.1.0 is released.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
The merge itself looks non-controversal to me. What's more controversal is removal of support for older requests, but I guess we're past that point.

**Comment by gavin-norman-sociomantic** [comment]
>The merge itself looks non-controversal to me. What's more controversal is removal of support for older requests, but I guess we're past that point.

As discussed elsewhere, we will remove support for all older requests when making this first "official" release of DMQ neo.

**Comment by gavin-norman-sociomantic** [comment]
@david-eckardt-sociomantic push at will.

**Comment by david-eckardt-sociomantic** [comment]
Pushed.

**Pull request merged**
