### PR TITLE
Update supported compiler matrix to match dhtnode

### PR DESCRIPTION
**Pull request by Geod24**
Remove support for v2.071, bump minimal version to v2.078 and add support for the latest release.

### CODE REVIEW

**Comment by Geod24** [comment]
```
+export DFLAGS=-vgc
+beaver dlang make d2conv
+/home/travis/build/sociomantic-tsunami/dmqnode/submodules/beaver/bin/beaver run make -rj2 d2conv
+docker run --rm -v /home/travis:/home/travis -v /home/travis/build/sociomantic-tsunami/dmqnode:/home/travis/build/sociomantic-tsunami/dmqnode -w /home/travis/build/sociomantic-tsunami/dmqnode -u 2000 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e USER -e HOME -e DEBIAN_FRONTEND -e RAILS_ENV -e RACK_ENV -e MERB_ENV -e JRUBY_OPTS -e JAVA_HOME -e CI -e CONTINUOUS_INTEGRATION -e TRAVIS_OS_NAME -e TRAVIS_STACK_LANGUAGES -e TRAVIS_APT_PROXY -e TRAVIS_BRANCH -e TRAVIS_SUDO -e TRAVIS_PRE_CHEF_BOOTSTRAP_TIME -e TRAVIS_PULL_REQUEST_BRANCH -e TRAVIS_BUILD_WEB_URL -e TRAVIS_BUILD_STAGE_NAME -e TRAVIS_PULL_REQUEST_SLUG -e TRAVIS_ROOT -e TRAVIS_ARCH -e TRAVIS_INTERNAL_RUBY_REGEX -e TRAVIS_ENABLE_INFRA_DETECTION -e TRAVIS_APP_HOST -e TRAVIS_COMMIT_MESSAGE -e TRAVIS_JOB_WEB_URL -e TRAVIS_INFRA -e TRAVIS_CMD -e TRAVIS_STACK_NAME -e TRAVIS_STACK_JOB_BOARD_REGISTER -e TRAVIS_JOB_NAME -e TRAVIS_REPO_SLUG -e TRAVIS_BUILD_ID -e TRAVIS_COMMIT_RANGE -e TRAVIS -e TRAVIS_ALLOW_FAILURE -e TRAVIS_EVENT_TYPE -e TRAVIS_STACK_FEATURES -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_DIR -e TRAVIS_HOME -e TRAVIS_SECURE_ENV_VARS -e TRAVIS_TAG -e TRAVIS_JOB_ID -e TRAVIS_COMMIT -e TRAVIS_CPU_ARCH -e TRAVIS_TIMER_START_TIME -e TRAVIS_PULL_REQUEST -e TRAVIS_STACK_TIMESTAMP -e TRAVIS_JOB_NUMBER -e TRAVIS_UID -e TRAVIS_PULL_REQUEST_SHA -e TRAVIS_LANGUAGE -e TRAVIS_STACK_NODE_ATTRIBUTES -e TRAVIS_DIST -e TRAVIS_TMPDIR -e TRAVIS_INIT -e TRAVIS_TEST_RESULT -e TRAVIS_TIMER_ID -e TRAVIS_OSX_IMAGE -e DIST -e DMD -e DC -e DVER -e D2_ONLY -e DFLAGS -e F -e V -e COV -e COVDIR -e COVMERGE builder make -rj2 d2conv
   d1to2fix build/devel/tmp/d2conv.stamp
/bin/sh: 1: d1to2fix: not found
make: *** [/home/travis/build/sociomantic-tsunami/dmqnode/build/devel/tmp/d2conv.stamp] Error 127
```

Looks like a bug in Beaver, there's a `.D2-only` which contains `ONLY`...

**Comment by Geod24** [comment]
Ah, thought the closure script was shared, but no.
Updated according to https://github.com/sociomantic-tsunami/ocean/blob/v5.x.x/ci/closures.sh

**Review by ibuclaw — APPROVED** [review]

**Comment by Geod24** [comment]
And I have to fix turtle:
```
integrationtest/ovfminimize/main.d(97): vgc: using closure causes GC allocation
./submodules/turtle/src/turtle/runner/actions/List.d(105): vgc: using closure causes GC allocation
./submodules/turtle/src/turtle/runner/actions/RunAll.d(46): vgc: using closure causes GC allocation
integrationtest/loadfiles/cases/checker/CheckedRequests.d(249): vgc: using closure causes GC allocation
```

**Comment by Geod24** [comment]
Green at last!

**Pull request merged**
